name: PokemonAPI
on:
  push:
  
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Setup Java JDK
      uses: actions/setup-java@v3.2.0
      with:
        distribution: temurin
        java-version: 11
    - name: Run tests
      run: ./gradlew --version 
           ./gradlew testDebugUnitTest --info
